org: lonestarresumes
app: resume-builder
service: resume-builder-api

# Create an optimized package for our functions 
package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  # To load environment variables externally
  # rename env.example to .env and uncomment
  # the following line. Also, make sure to not
  # commit your .env.
  #
  environment:
    tableName: resumes
  #  SAMPLE_ENV_VAR: ${env:SAMPLE_ENV_VAR}

functions:
  create:
    handler: api/create.main
    events:
      - http:
          path: resume
          method: post

  get:
    handler: api/get.main
    events:
      - http:
          path: resume/{id}
          method: get
  
  list:
    handler: api/list.main
    events:
      - http:
          path: resume
          method: get
  
  update:
    handler: api/update.main
    events:
      - http:
          path: resume/{id}
          method: put
  
  delete:
    handler: api/delete.main
    events:
      - http:
          path: resume/{id}
          method: delete